### ISSUE TITLE
my affiliation is showing up as 23 in the proofs, is this normal?

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#322] opened 2022-03-03 11:28 UTC

**Comment by Anaphory** [comment] 2022-03-03 21:11
There was an issue when I first asked Whedon to compile the PDF, and someone of the JOSS people told me to use the way that's in the paper's front matter now, so I assume this is working as intended.

**Comment by Bisaloo** [comment] 2022-03-07 15:13
I double checked in a couple of recently published JOSS articles and this seems to be the normal format for multiple affiliations indeed.

https://joss.theoj.org/papers/10.21105/joss.03980
https://joss.theoj.org/papers/10.21105/joss.03574

**Closed** 2022-03-07 23:24 UTC
